### ISSUE TITLE
terraform lifecycle

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium-terraform#6]
- should the tfstate storage have a separate life cylce
  - if you run tf destroy, the state file is gone forever

- in our design, we create 3 RGs because they have different life cycles. in TF, we munge them all together.
  - should Cosmos have a separate life cycle?
  - should ACR have a separate life cycle?

**Comment by evillgenius75** [comment]
Following a code review the following possible fixes have been found:
- TFState code is in the incorrect location and TF does not support Variable interpolation for backend state information
- The alert resources are very repetitive with the same parameters which required numerous variables. This can be solved by using a map object and a for_each to reduce the complexity
- The create_tfvars.sh file can be used to also create the required data for the tfstate information by writing out a main_tfstate.tf file
- update the TF to 0.13 and remove old style module dependency and update to new module dependency
